[project]
name = "bento-model-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bentoml>=1.4.15",
    "pydantic>=2.11.5",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]
