[project]
name = "mlflow-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.23",
    "cryptography>=45.0.3",
    "mlflow>=2.22.0",
    "psycopg2-binary>=2.9.10",
    "pymysql>=1.1.1",
]
